const DUNGEONS = [
  {
    name: '青云秘境',
    danger: 1,
    minRealm: 0,
    qiCost: 8,
    description: '云雾中的旧修士遗址，适合初次试炼。',
    cultivation: [8, 15],
    spiritHerbs: [1, 2],
    qiPillChance: 0.08,
  },
  {
    name: '玄冰窟',
    danger: 2,
    minRealm: 1,
    qiCost: 14,
    description: '寒气侵骨，冰层下偶有灵草与旧药瓶。',
    cultivation: [12, 22],
    spiritHerbs: [1, 3],
    qiPillChance: 0.12,
  },
  {
    name: '血煞洞',
    danger: 3,
    minRealm: 1,
    qiCost: 22,
    description: '煞气盘踞的裂谷，留下了许多危险气息。',
    cultivation: [18, 30],
    spiritHerbs: [1, 2],
    qiPillChance: 0.18,
  },
  {
    name: '古战场',
    danger: 3,
    minRealm: 2,
    qiCost: 26,
    description: '残兵与阵痕之间，仍有未散的战意。',
    cultivation: [24, 38],
    spiritHerbs: [1, 3],
    qiPillChance: 0.2,
  },
  {
    name: '雷鸣谷',
    danger: 4,
    minRealm: 2,
    qiCost: 35,
    description: '雷霆反复落下，谷底藏着淬体机缘。',
    cultivation: [30, 48],
    spiritHerbs: [1, 3],
    qiPillChance: 0.24,
  },
  {
    name: '万兽岭',
    danger: 4,
    minRealm: 3,
    qiCost: 40,
    description: '群兽出没的山岭，资源丰富但不能久留。',
    cultivation: [36, 56],
    spiritHerbs: [2, 4],
    qiPillChance: 0.26,
  },
  {
    name: '天火秘境',
    danger: 5,
    minRealm: 3,
    qiCost: 52,
    description: '地火翻涌的秘境，灵材和危险同时增长。',
    cultivation: [45, 68],
    spiritHerbs: [2, 5],
    qiPillChance: 0.3,
  },
  {
    name: '黄泉地宫',
    danger: 5,
    minRealm: 4,
    qiCost: 58,
    description: '幽暗地宫深不见底，回声里藏着古老传承。',
    cultivation: [52, 78],
    spiritHerbs: [2, 4],
    qiPillChance: 0.34,
  },
  {
    name: '地脉矿窟',
    danger: 2,
    minRealm: 1,
    qiCost: 18,
    description: '地脉交汇的矿洞，灵气稳定，适合反复探索。',
    cultivation: [14, 25],
    spiritHerbs: [2, 4],
    qiPillChance: 0.14,
  },
  {
    name: '迷雾禁地',
    danger: 4,
    minRealm: 3,
    qiCost: 46,
    description: '迷雾遮蔽方向，只有守住心神才能带回收获。',
    cultivation: [40, 62],
    spiritHerbs: [1, 4],
    qiPillChance: 0.28,
  },
  {
    name: '幽冥墓',
    danger: 5,
    minRealm: 4,
    qiCost: 62,
    description: '古墓阴气未散，偶尔能寻到失传的丹药。',
    cultivation: [58, 86],
    spiritHerbs: [1, 3],
    qiPillChance: 0.38,
  },
  {
    name: '妖王巢穴',
    danger: 6,
    minRealm: 5,
    qiCost: 80,
    description: '妖王盘踞之所，只有做好准备才值得冒险。',
    cultivation: [75, 110],
    spiritHerbs: [3, 6],
    qiPillChance: 0.45,
  },
  {
    name: '断魂崖',
    danger: 3,
    minRealm: 2,
    qiCost: 30,
    description: '峭壁罡风不断，崖缝中常有孤生灵草。',
    cultivation: [26, 42],
    spiritHerbs: [2, 4],
    qiPillChance: 0.22,
  },
];

export default DUNGEONS;
export { DUNGEONS };
