const CAVE_BUILDINGS = [
  {
    id: 'mainHall',
    name: '洞府主室',
    shortName: '主室',
    row: 0,
    col: 1,
    status: '损坏',
    effect: '修缮后启用洞府核心功能',
    maxLevel: 6,
    levelEffects: ['提高洞府灵气上限', '提高洞府灵气上限', '解锁新的建筑位置', '提高洞府灵气上限', '解锁高阶洞府功能', '洞府核心完全复苏'],
    action: null,
  },
  {
    id: 'spiritArray',
    name: '聚灵阵',
    shortName: '聚灵',
    row: 0,
    col: 6,
    status: '损坏',
    effect: '修缮后开始产出灵气',
    maxLevel: 6,
    levelEffects: ['每分钟产出2点灵气', '每分钟产出4点灵气', '每分钟产出7点灵气', '每分钟产出11点灵气', '每分钟产出16点灵气', '每分钟产出22点灵气'],
    action: '收取灵气',
  },
  {
    id: 'spiritField',
    name: '灵田',
    shortName: '灵田',
    row: 2,
    col: 2,
    status: '损坏',
    effect: '修缮后可种植灵草',
    maxLevel: 6,
    levelEffects: ['开放1个种植位', '开放2个种植位', '开放3个种植位', '开放4个种植位', '开放6个种植位', '开放8个种植位'],
    action: '进入灵田',
  },
  {
    id: 'alchemyFurnace',
    name: '丹炉',
    shortName: '丹炉',
    row: 2,
    col: 5,
    status: '损坏',
    effect: '修缮后开放炼丹功能',
    maxLevel: 6,
    levelEffects: ['开放基础炼丹', '缩短炼丹时间', '开放2个炼丹队列', '开放中阶丹药', '提高丹药品质', '开放高阶丹药'],
    action: '进入炼丹',
  },
  {
    id: 'meditationRoom',
    name: '静室',
    shortName: '静室',
    row: 5,
    col: 1,
    status: '损坏',
    effect: '修缮后开放闭关修炼',
    maxLevel: 6,
    levelEffects: ['开放基础修炼', '修炼效率提高10%', '修炼效率提高20%', '修炼效率提高35%', '修炼效率提高55%', '修炼效率提高80%'],
    action: '进入修炼',
  },
  {
    id: 'scripturePavilion',
    name: '藏经阁',
    shortName: '藏经',
    row: 5,
    col: 6,
    status: '损坏',
    effect: '修缮后可研究功法',
    maxLevel: 6,
    levelEffects: ['开放功法研究', '增加功法槽位', '解锁新的功法', '解锁被动效果', '解锁高阶功法', '解锁传承功法'],
    action: '进入功法',
  },
];

export default CAVE_BUILDINGS;
export { CAVE_BUILDINGS };
